# Generated by Django 3.1.3 on 2020-11-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.IntegerField(unique=True),
        ),
    ]
