# Generated by Django 3.1.3 on 2020-11-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201118_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qt_stock',
            field=models.PositiveIntegerField(),
        ),
    ]
